version: '3.8'

services:
  api:
    build: .
    container_name: sinhronizuj-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - ./temp_workspace:/app/temp_workspace

  worker:
    build: .
    container_name: sinhronizuj-worker
    command: celery -A backend.worker.tasks worker --loglevel=info --concurrency=1
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - ./temp_workspace:/app/temp_workspace
      - .:/app # Za worker.log pristupačnost

  redis:
    image: redis:7-alpine
    container_name: sinhronizuj-redis
    ports:
      - "6379:6379"
