"""add active_speaker to segments

Revision ID: 9c09b48931b7
Revises: ab6cf7e00a69
Create Date: 2026-06-12 15:07:01.165708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c09b48931b7'
down_revision: Union[str, Sequence[str], None] = 'ab6cf7e00a69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('segments', sa.Column('active_speaker', sa.Boolean(), server_default='true', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('segments', 'active_speaker')
    # ### end Alembic commands ###
