"""add jobs table

Revision ID: 9d45a91db31f
Revises: d3b1029c8e9f
Create Date: 2026-06-20 04:06:40.874904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import backend


# revision identifiers, used by Alembic.
revision: str = '9d45a91db31f'
down_revision: Union[str, Sequence[str], None] = 'd3b1029c8e9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', backend.core.models.GUID(), nullable=False),
    sa.Column('project_id', backend.core.models.GUID(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('current_phase', sa.String(), nullable=True),
    sa.Column('attempt', sa.Integer(), server_default='1', nullable=True),
    sa.Column('current_artifact_keys', sa.JSON(), nullable=True),
    sa.Column('error_code', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jobs')
    # ### end Alembic commands ###
