"""Initial migration

Revision ID: ab6cf7e00a69
Revises: 
Create Date: 2026-06-12 07:55:13.872640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import backend


# revision identifiers, used by Alembic.
revision: str = 'ab6cf7e00a69'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', backend.core.models.GUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('waitlist',
    sa.Column('id', backend.core.models.GUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_waitlist_email'), 'waitlist', ['email'], unique=True)
    op.create_table('glossaries',
    sa.Column('id', backend.core.models.GUID(), nullable=False),
    sa.Column('user_id', backend.core.models.GUID(), nullable=False),
    sa.Column('source_word', sa.String(), nullable=False),
    sa.Column('target_word', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', backend.core.models.GUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('user_id', backend.core.models.GUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('video_title', sa.String(), nullable=True),
    sa.Column('video_s3_key', sa.String(), nullable=True),
    sa.Column('vocals_s3_key', sa.String(), nullable=True),
    sa.Column('no_vocals_s3_key', sa.String(), nullable=True),
    sa.Column('visual_context_s3_key', sa.String(), nullable=True),
    sa.Column('dubbed_audio_s3_key', sa.String(), nullable=True),
    sa.Column('final_video_s3_key', sa.String(), nullable=True),
    sa.Column('costs', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('segments',
    sa.Column('project_id', backend.core.models.GUID(), nullable=False),
    sa.Column('segment_id', sa.Integer(), nullable=False),
    sa.Column('start', sa.Float(), nullable=False),
    sa.Column('end', sa.Float(), nullable=False),
    sa.Column('original', sa.String(), nullable=True),
    sa.Column('translated', sa.String(), nullable=True),
    sa.Column('voice_type', sa.String(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.Column('pitch', sa.Float(), nullable=True),
    sa.Column('bg_volume', sa.Float(), nullable=True),
    sa.Column('tts_s3_key', sa.String(), nullable=True),
    sa.Column('tts_duration', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'segment_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('segments')
    op.drop_table('projects')
    op.drop_table('glossaries')
    op.drop_index(op.f('ix_waitlist_email'), table_name='waitlist')
    op.drop_table('waitlist')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
