import os
import base64
import re
from backend.core.config import settings

def segment_by_sentences(segments):
    if not segments:
        return []
        
    # 1. Izvlačimo sve reči u jedan linearan niz radi lakše analize pauza
    all_words = []
    for s in segments:
        if "words" in s and s["words"]:
            all_words.extend(s["words"])
        else:
            # Fallback ako nema word_timestamps: podeli tekst segmenta na reči (manje precizno)
            words = s["text"].split()
            if not words: continue
            dur = (s["end"] - s["start"]) / len(words)
            for i, w in enumerate(words):
                all_words.append({
                    "start": s["start"] + i*dur,
                    "end": s["start"] + (i+1)*dur,
                    "word": w
                })

    if not all_words:
        return []

    # 2. Grupišemo reči u rečenice na osnovu interpunkcije I pauza
    sentence_segments = []
    curr_words = []
    
    for i in range(len(all_words)):
        w = all_words[i]
        curr_words.append(w)
        
        word_text = w["word"].strip()
        
        # Provera interpunkcije na samoj reči
        has_punct = any(word_text.endswith(p) for p in ['.', '!', '?', '...'])
        
        # Provera pauze do sledeće reči
        has_pause = False
        if i < len(all_words) - 1:
            pause_duration = all_words[i+1]["start"] - w["end"]
            if pause_duration > 0.45: # Pauza duža od 0.45s je obično kraj rečenice
                has_pause = True
        
        # Opušteniji limit: režemo tek na 40 reči ako baš nema ni tačke ni pauze.
        # Ako ima zarez a prešli smo 20 reči, režemo tu da sprečimo gigantske segmente.
        is_too_long = len(curr_words) >= 40
        has_comma_and_long = word_text.endswith(',') and len(curr_words) >= 20
        
        if has_punct or has_pause or is_too_long or has_comma_and_long:
            text = " ".join([cw["word"].strip() for cw in curr_words])
            sentence_segments.append({
                "start": round(curr_words[0]["start"], 2),
                "end": round(curr_words[-1]["end"], 2),
                "text": text
            })
            curr_words = []
            
    # Dodajemo preostale reči
    if curr_words:
        text = " ".join([cw["word"].strip() for cw in curr_words])
        sentence_segments.append({
            "start": round(curr_words[0]["start"], 2),
            "end": round(curr_words[-1]["end"], 2),
            "text": text
        })
        
    return sentence_segments

def arbitrate_transcripts(whisper_segments: list, sensevoice_text: str) -> list:
    """
    Poziva Lektor (Qwen 32B) da na osnovu kompletnog SenseVoice transkripta (koji je druga perspektiva)
    koriguje pojedinačne Whisper segmente bez menjanja vremenskih intervala.
    """
    if not settings.MODAL_LEKTOR_URL or not sensevoice_text:
        return whisper_segments
        
    print("[ARBITRAŽA] Pokrećem LLM arbitražu transkripata...")
    
    # Pripremamo Whisper segmente u formatu pogodnom za LLM
    whisper_input = ""
    for i, seg in enumerate(whisper_segments):
        whisper_input += f"[seg-{i}] {seg['text']}\n"
        
    arbitration_prompt = (
        "You are an expert English audio transcript editor.\n"
        "I will provide you with two things:\n"
        "1. A list of tagged text segments generated by Whisper ASR (which has word timestamps but might have misheard or missing words).\n"
        "2. A full raw text transcript of the same audio generated by another model (SenseVoice) which is very accurate at spelling but lacks timestamps.\n\n"
        "YOUR TASK:\n"
        "Review each Whisper segment. Compare it with the SenseVoice transcript and context.\n"
        "If you spot a transcription error in a Whisper segment (e.g., spelling of technical terms like 'Vite' instead of 'white', 'Modal', 'RunPod', missing small words, or punctuation errors), CORRECT the text.\n"
        "Do NOT change the meaning or translate. Output the corrected segments.\n\n"
        "CRITICAL RULES FOR SEGMENTS:\n"
        "1. STRICT LINE CORRESPONDENCE: You must preserve the exact boundaries of each segment. Do NOT merge multiple segments, do NOT split segments, and do NOT skip any segments.\n"
        "2. Each input segment tag [seg-ID] must correspond to exactly one output line with the same tag.\n"
        "3. If a sentence in the SenseVoice transcript is split across two Whisper segments, KEEP them split across those same segments. Do not combine them under a single tag.\n\n"
        "CRITICAL FORMAT RULES:\n"
        "1. Output exactly one line per segment in the format: [seg-ID] Corrected text\n"
        f"2. You must output exactly {len(whisper_segments)} lines (from [seg-0] to [seg-{len(whisper_segments)-1}]).\n"
        "3. Do not include any introduction, explanation, or code blocks. Just the [seg-ID] text lines.\n\n"
        f"FULL SENSEVOICE TRANSCRIPT:\n{sensevoice_text}\n\n"
        f"WHISPER SEGMENTS FOR CORRECTION:\n{whisper_input}"
    )
    
    from backend.worker.utils import call_modal_endpoint
    try:
        payload = {
            "model": "qwen-lektor",
            "messages": [{"role": "user", "content": arbitration_prompt}],
            "temperature": 0.1,
            "max_tokens": 1500
        }
        url = f"{settings.MODAL_LEKTOR_URL.rstrip('/')}/v1/chat/completions"
        
        # Pozivamo Lektor endpoint
        output = call_modal_endpoint(
            url=url,
            payload=payload,
            timeout_seconds=600,
            progress_callback=None
        )
        
        try:
            raw_output = output["choices"][0]["message"]["content"]
        except (KeyError, IndexError):
            raw_output = str(output)
            
        print(f"[DEBUG] ARBITRATION OUTPUT: {raw_output[:500]}...", flush=True)
        
        # Parsiranje rezultata
        parsed_dict = {}
        for line in raw_output.split('\n'):
            line = line.strip()
            if not line or '[seg-' not in line:
                continue
            match = re.match(r'\[seg-(\d+)\]\s*(.*)', line)
            if match:
                try:
                    idx = int(match.group(1))
                    text = match.group(2).strip()
                    if text:
                        parsed_dict[idx] = text
                except ValueError:
                    continue
                    
        # Vraćamo ažurirane segmente sa sačuvanim tajminzima
        corrected_segments = []
        for i, orig in enumerate(whisper_segments):
            t_text = parsed_dict.get(i, orig["text"])
            corrected_segments.append({
                "start": orig["start"],
                "end": orig["end"],
                "text": t_text
            })
        return corrected_segments
        
    except Exception as e:
        print(f"[WARNING] Arbitraža nije uspela: {e}. Vraćam originalne Whisper segmente.")
        return whisper_segments

def transcribe_audio(audio_path: str, initial_prompt: str = None, progress_callback=None) -> dict:
    if not os.path.exists(audio_path):
        return {"status": "error", "message": f"Fajl nije pronađen: {audio_path}"}

    # KORAK 2: Normalizacija zvuka
    from backend.worker.utils import normalize_audio
    try:
        normalize_audio(audio_path, target_dbfs=-20.0)
    except Exception as e:
        print(f"[WARNING] Normalizacija zvuka nije uspela: {e}")

    try:
        with open(audio_path, "rb") as audio_file:
            audio_base64 = base64.b64encode(audio_file.read()).decode('utf-8')
    except Exception as e:
        return {"status": "error", "message": f"Greška pri čitanju audia: {e}"}

    from backend.worker.utils import call_modal_endpoint
    import concurrent.futures

    # Definišemo paralelne ASR pozive
    def run_whisper():
        print("[ASR] Pokrećem Whisper transkripciju...", flush=True)
        payload = {
            "task": "transcribe", 
            "audio_base64": audio_base64,
            "vad_filter": False,
            "condition_on_previous_text": True,
            "word_timestamps": False,
            "no_speech_threshold": None,
            "log_prob_threshold": None,
            "compression_ratio_threshold": None
        }
        if initial_prompt:
            payload["initial_prompt"] = initial_prompt
            
        return call_modal_endpoint(
            url=settings.MODAL_STT_URL, 
            payload=payload, 
            timeout_seconds=900,
            progress_callback=progress_callback
        )

    def run_sensevoice():
        if not settings.MODAL_SENSEVOICE_URL:
            print("[ASR] SenseVoice URL nije konfigurisan. Preskačem sekundarni model.", flush=True)
            return None
        print("[ASR] Pokrećem SenseVoice transkripciju...", flush=True)
        payload = {"audio_base64": audio_base64}
        try:
            return call_modal_endpoint(
                url=settings.MODAL_SENSEVOICE_URL,
                payload=payload,
                timeout_seconds=600,
                progress_callback=None
            )
        except Exception as e:
            print(f"[WARNING] SenseVoice transkripcija podbila: {e}", flush=True)
            return None

    try:
        whisper_output = None
        sensevoice_output = None
        
        # Izvršavamo ASR pozive paralelno
        with concurrent.futures.ThreadPoolExecutor(max_workers=2) as executor:
            future_whisper = executor.submit(run_whisper)
            future_sensevoice = executor.submit(run_sensevoice)
            
            whisper_output = future_whisper.result()
            sensevoice_output = future_sensevoice.result()
            
        raw_segments = whisper_output.get("segments", [])
        sentence_segments = segment_by_sentences(raw_segments)
        
        sensevoice_text = ""
        if sensevoice_output:
            sensevoice_text = sensevoice_output.get("text", "")
            
        # KORAK 4: LLM Arbitraža ako imamo oba transkripta
        if sentence_segments and sensevoice_text:
            print(f"[ASR] Uspešno pribavljena oba transkripta. Pokrećem arbitražu.", flush=True)
            sentence_segments = arbitrate_transcripts(sentence_segments, sensevoice_text)
        
        return {
            "status": "success",
            "language": whisper_output.get("language", "unknown"),
            "full_text": " ".join([s["text"] for s in sentence_segments]),
            "segments": sentence_segments
        }
    except Exception as e:
        return {"status": "error", "message": str(e)}

